site_name: KtMongo (experimental)
site_author: 4SH & contributors
site_description: >
  Towards the future of MongoDB in Kotlin.
repo_url: https://github.com/4sh/ktmongo
repo_name: 4SH / KtMongo

theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: "System theme (click to switch to light)"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: "Light theme (click to switch to dark)"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: "Dark theme (click to switch to system)"

plugins:
  - social

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

edit_uri: edit/main/docs/website/docs

use_directory_urls: false

nav:
  - Home: index.md

  - Getting started:
      - guides/overview.md
      - guides/setup.md
      - guides/search.md
      - guides/update.md

  - Migrating from KMongo:
      - migrate-from-kmongo/why.md
      - migrate-from-kmongo/setup.md
      - migrate-from-kmongo/search.md
      - migrate-from-kmongo/nested-fields.md
