site_name: KtMongo (experimental)
site_author: 4SH & contributors
site_description: >
  Towards the future of MongoDB in Kotlin.
repo_url: https://github.com/4sh/ktmongo
repo_name: 4SH / KtMongo

theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: "System theme (click to switch to light)"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: "Light theme (click to switch to dark)"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: "Dark theme (click to switch to system)"

plugins:
  - social

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

edit_uri: edit/main/docs/website/docs

use_directory_urls: false

nav:
  - Home: index.md

  - Getting started:
      - guides/overview.md
      - guides/setup.md
      - guides/search.md

  - Migrating from KMongo:
      - migrate-from-kmongo/why.md
      - migrate-from-kmongo/setup.md
      - migrate-from-kmongo/search.md
      - migrate-from-kmongo/nested-fields.md

  - Reference:
      - DSL:
          - reference-dsl/index.md
          - fr.qsh.ktmongo.dsl:
              - reference-dsl/dsl/fr.qsh.ktmongo.dsl/index.md
              - KtMongoDsl: reference-dsl/dsl/fr.qsh.ktmongo.dsl/-kt-mongo-dsl/index.md
              - LowLevelApi: reference-dsl/dsl/fr.qsh.ktmongo.dsl/-low-level-api/index.md
          - fr.qsh.ktmongo.dsl.expr:
              - reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/index.md
              - FilterExpression:
                  - reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/index.md
                  - accept: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/accept.md
                  - acceptAll: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/accept-all.md
                  - and: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/and.md
                  - doesNotExist: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/does-not-exist.md
                  - eq: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/eq.md
                  - eqNotNull: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/eq-not-null.md
                  - exists: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/exists.md
                  - freeze: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/freeze.md
                  - gt: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/gt.md
                  - gte: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/gte.md
                  - gteNotNull: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/gte-not-null.md
                  - gtNotNull: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/gt-not-null.md
                  - hasType: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/has-type.md
                  - invoke: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/invoke.md
                  - isNotNull: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/is-not-null.md
                  - isNotUndefined: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/is-not-undefined.md
                  - isNull: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/is-null.md
                  - isOneOf: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/is-one-of.md
                  - isUndefined: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/is-undefined.md
                  - lt: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/lt.md
                  - lte: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/lte.md
                  - lteNotNull: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/lte-not-null.md
                  - ne: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/ne.md
                  - not: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/not.md
                  - or: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/or.md
                  - simplify: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/simplify.md
                  - writeTo: reference-dsl/dsl/fr.qsh.ktmongo.dsl.expr/-filter-expression/writeTo.md
